# Input Variables
#    MODELE_ROOT
# Produces:
#    MODELE_LIBRARY
#    MODELE_INCLUDE_DIR


FIND_PATH(MODELE_INCLUDE_DIR diag_zonal.mod
	HINTS ${MODELE_ROOT}/include)

FIND_LIBRARY(MODELE_LIBRARY NAMES modele
	HINTS ${MODELE_ROOT}/lib)

IF (MODELE_INCLUDE_DIR AND MODELE_LIBRARY)
   SET(MODELE_FOUND TRUE)
ENDIF (MODELE_INCLUDE_DIR AND MODELE_LIBRARY)

IF (MODELE_FOUND)
   IF (NOT MODELE_FIND_QUIETLY)
      MESSAGE(STATUS "Found  xxx MODELE_LIBRARY: ${MODELE_LIBRARY}")
      MESSAGE(STATUS "Found  xxx MODELE_INCLUDE_DIR: ${MODELE_INCLUDE_DIR}")
   ENDIF (NOT MODELE_FIND_QUIETLY)
ELSE (MODELE_FOUND)
   IF (MODELE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find MODELE")
   ENDIF (MODELE_FIND_REQUIRED)
ENDIF (MODELE_FOUND)
